### ISSUE TITLE
isSelector is Overly Aggressive

### ISSUE THREAD

**Issue by emmercm** [vitaliy-bobrov/metalsmith-twitter-card#2]
`isSelector()` as defined here:

https://github.com/vitaliy-bobrov/metalsmith-twitter-card/blob/d8dfc3c63aa0a8c0d01fd8367859df7f8da942a4/lib/index.js#L126

Incorrectly returns `true` for titles or descriptions such as `...lorem ipsum` that start with an ellipsis. It also doesn't allow for tag names to come first in the selector.

Maybe a better way would be to check `el` to see if it found any results here:

https://github.com/vitaliy-bobrov/metalsmith-twitter-card/blob/d8dfc3c63aa0a8c0d01fd8367859df7f8da942a4/lib/index.js#L145

**Comment by vitaliy-bobrov** [comment]
Hi @emmercm, thanks for the suggestion, I've changed the CSS selector validation!

**Comment by emmercm** [comment]
https://github.com/vitaliy-bobrov/metalsmith-twitter-card/commit/3b8421e0fb0d0262aa57605776b866e6b17f34c0#diff-6d186b954a58d5bb740f73d84fe39073R146

This line is causing a: `ReferenceError: $ is not defined` in v1.0.6.
